# Generated by Django 4.0.3 on 2022-04-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_video_description_alter_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=models.CharField(max_length=100), max_length=50),
        ),
    ]
