# Generated by Django 4.0.3 on 2022-04-08 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_user_staffstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='staffstatus',
            new_name='staff_status',
        ),
    ]
