# Generated by Django 4.0.3 on 2022-04-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_rename_staffstatus_user_staff_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
