# Generated by Django 4.0.3 on 2022-04-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='staff_status',
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(default='new questioon', max_length=300),
            preserve_default=False,
        ),
    ]
