# Generated by Django 4.0.3 on 2022-04-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_video_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter image Title', max_length=50)),
                ('picture', models.FileField(upload_to='pictures/')),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(help_text='Enter Video Category', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
    ]
