# Generated by Django 4.0.3 on 2022-04-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_video_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, help_text='image Description', null=True),
        ),
    ]
