# Generated by Django 4.0.3 on 2022-04-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_comment_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comm',
        ),
    ]
