# Generated by Django 4.0.3 on 2022-04-03 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_rename_body_comment_comm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comm',
            new_name='commenting',
        ),
    ]
