# Generated by Django 4.0.3 on 2022-04-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_video_uploaded_by_alter_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
