# Generated by Django 4.0.3 on 2022-04-04 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_alter_comment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='video',
        ),
    ]
