# Generated by Django 4.0.3 on 2022-04-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_remove_video_uploaded_by_comment_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
    ]
