# Generated by Django 4.0.3 on 2022-04-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_question'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
    ]
