# Generated by Django 4.0.3 on 2022-04-06 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_alter_question_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
    ]
